In [2]:
import pandapower as pp #import pandapower
import numpy as np
import pandapower.networks as pn 
from pandapower.estimation import estimate
import pandapower.plotting as plot
%matplotlib inline
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'pandapower'

## IEEE 39-Bus System
The â€œIEEE 39 bus system is well known as 10-machine New-England Power System. Generator 1 represents the aggregation of a large number of generators.
<img src="pics/IEEE39.png" width="600">

Calls the pickle file case39.p which data origin is PYPOWER. This network was published the first time in
G. Bills et al., On-line stability analysis study, RP 90-1, E. P. R. I. North American Rockwell Corporation,
Edison Electric Institute, Ed. IEEE Press, Oct. 1970,. Some more information about this network are
given by Illinois University case 39. Because the Pypower data origin proposes vn_kv=345 for all nodes
the transformers connect node of the same voltage level.

In [3]:
net = pn.case39()

NameError: name 'pn' is not defined

In [4]:
net

NameError: name 'net' is not defined

In [5]:
net.res_bus

NameError: name 'net' is not defined

In [6]:
net_val = net.res_bus.values
net_index = net.res_bus.index.values

In [7]:
net_val.shape, net_index.shape

((39, 4), (39,))

In [8]:
net_arr = np.c_[net_index,net_val]

In [9]:
net_arr.shape

(39, 5)

In [41]:
sigma_vm = 0.1
sigma_p = 20
sigma_q = 20
measurment_index = net_arr[:,0].astype(int)
measurment_vm = net_arr[:,1] + np.random.normal(0,sigma_vm,net_arr.shape[0])
measurment_p = -net_arr[:,3] + np.random.normal(0,sigma_p,net_arr.shape[0])
measurment_q = -net_arr[:,4] + np.random.normal(0,sigma_q,net_arr.shape[0])

In [42]:
measurment_index, measurment_vm,measurment_p,measurment_q

(array([ 0,  1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,  2, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29,  3, 30, 31, 32, 33, 34, 35, 36, 37, 38,  4,
         5,  6,  7,  8,  9]),
 array([1.11744776, 1.06914763, 0.82595361, 0.98316306, 1.11289383,
        1.08030694, 1.06532005, 1.0269896 , 1.04089473, 0.97874081,
        1.14465597, 0.84958137, 1.11076376, 0.83378339, 0.9757169 ,
        0.98332318, 1.12289955, 1.24845562, 1.24434029, 1.11081354,
        1.13232227, 0.9618305 , 1.12142019, 0.96208052, 0.9441451 ,
        1.0299535 , 0.88702882, 1.09001468, 1.00587924, 0.89596414,
        1.01314061, 1.08581849, 1.09213031, 0.93625069, 1.31488458,
        1.05385149, 0.86303378, 1.00792962, 1.086692  ]),
 array([-9.76007324e+04,  2.80651527e+01,  1.54765211e+01, -8.52849701e+03,
        -1.24615894e+01, -3.63881231e+00, -3.20042401e+05, -3.28977402e+05,
        -3.64248449e+01, -1.57993461e+05,  3.14956939e+01, -6.79991377e+05,
        -3.21960489e+05, -2.74001437e+05, -1.92186131e+01, -2.47498927e+05,
        -3.08579634e+05, -2.23972481e+05, -1.39013132e+05, -2.81002822e+05,
        -2.05998494e+05, -2.83485984e+05,  2.50014129e+05, -4.99997038e+05,
         6.68699798e+05,  6.49971178e+05,  6.31990449e+05,  5.08020597e+05,
         6.49990505e+05,  5.59975721e+05,  5.39997616e+05,  8.30003841e+05,
        -1.04038781e+05,  6.85009327e+00,  2.56672760e+01, -2.33825346e+05,
        -5.21984454e+05, -6.49504463e+03,  3.91904418e+01]),
 array([-4.41940865e+04,  8.14638051e+00,  6.96238461e-01, -8.80359323e+04,
         4.56573568e+00, -2.39942237e+00, -1.53028059e+05, -3.22958709e+04,
        -2.09942441e+01, -3.00230342e+04, -1.81004339e+01, -1.03009297e+05,
        -2.37333487e+03, -1.14982549e+05,  2.35753741e+01, -8.45946400e+04,
         9.21839802e+04, -4.72071249e+04, -1.69796740e+04, -7.55395732e+04,
        -2.76035135e+04, -2.69108797e+04,  1.61766979e+05, -1.84002254e+05,
         2.16958782e+05,  2.06960154e+05,  1.08298786e+05,  1.66730546e+05,
         2.10662705e+05,  1.00193127e+05, -1.38220644e+03,  2.17256468e+04,
        -1.71555988e+05, -3.15658583e+00,  1.64175801e+01, -8.39923056e+04,
        -1.76615595e+05,  6.66073354e+04, -6.74288419e+00]))

In [43]:
measurment_vm[0]

1.1174477595120278

In [44]:
for i in range(net_arr.shape[0]):
    pp.create_measurement(net, "v", "bus", measurment_vm[i], sigma_vm, measurment_index[i])
    pp.create_measurement(net, "p", "bus", measurment_p[i], sigma_p, measurment_index[i])        
    pp.create_measurement(net, "q", "bus", measurment_q[i], sigma_q, measurment_index[i]) 
net.measurement

     name type element_type          value  std_dev  bus element
0    None    v          bus       1.117448      0.1    0    None
1    None    p          bus  -97600.732361     20.0    0    None
2    None    q          bus  -44194.086515     20.0    0    None
3    None    v          bus       1.069148      0.1    1    None
4    None    p          bus      28.065153     20.0    1    None
5    None    q          bus       8.146381     20.0    1    None
6    None    v          bus       0.825954      0.1   10    None
7    None    p          bus      15.476521     20.0   10    None
8    None    q          bus       0.696238     20.0   10    None
9    None    v          bus       0.983163      0.1   11    None
10   None    p          bus   -8528.497007     20.0   11    None
11   None    q          bus  -88035.932298     20.0   11    None
12   None    v          bus       1.112894      0.1   12    None
13   None    p          bus     -12.461589     20.0   12    None
14   None    q          bus       4.565736     20.0   12    None
15   None    v          bus       1.080307      0.1   13    None
16   None    p          bus      -3.638812     20.0   13    None
17   None    q          bus      -2.399422     20.0   13    None
18   None    v          bus       1.065320      0.1   14    None
19   None    p          bus -320042.400989     20.0   14    None
20   None    q          bus -153028.058567     20.0   14    None
21   None    v          bus       1.026990      0.1   15    None
22   None    p          bus -328977.401729     20.0   15    None
23   None    q          bus  -32295.870937     20.0   15    None
24   None    v          bus       1.040895      0.1   16    None
25   None    p          bus     -36.424845     20.0   16    None
26   None    q          bus     -20.994244     20.0   16    None
27   None    v          bus       0.978741      0.1   17    None
28   None    p          bus -157993.460765     20.0   17    None
29   None    q          bus  -30023.034233     20.0   17    None
..    ...  ...          ...            ...      ...  ...     ...
87   None    v          bus       0.895964      0.1   35    None
88   None    p          bus  559975.721467     20.0   35    None
89   None    q          bus  100193.126695     20.0   35    None
90   None    v          bus       1.013141      0.1   36    None
91   None    p          bus  539997.616399     20.0   36    None
92   None    q          bus   -1382.206438     20.0   36    None
93   None    v          bus       1.085818      0.1   37    None
94   None    p          bus  830003.840594     20.0   37    None
95   None    q          bus   21725.646812     20.0   37    None
96   None    v          bus       1.092130      0.1   38    None
97   None    p          bus -104038.781409     20.0   38    None
98   None    q          bus -171555.987931     20.0   38    None
99   None    v          bus       0.936251      0.1    4    None
100  None    p          bus       6.850093     20.0    4    None
101  None    q          bus      -3.156586     20.0    4    None
102  None    v          bus       1.314885      0.1    5    None
103  None    p          bus      25.667276     20.0    5    None
104  None    q          bus      16.417580     20.0    5    None
105  None    v          bus       1.053851      0.1    6    None
106  None    p          bus -233825.345771     20.0    6    None
107  None    q          bus  -83992.305641     20.0    6    None
108  None    v          bus       0.863034      0.1    7    None
109  None    p          bus -521984.454092     20.0    7    None
110  None    q          bus -176615.594689     20.0    7    None
111  None    v          bus       1.007930      0.1    8    None
112  None    p          bus   -6495.044631     20.0    8    None
113  None    q          bus   66607.335440     20.0    8    None
114  None    v          bus       1.086692      0.1    9    None
115  None    p          bus      39.190442     20.0    9    None
116  None    q          bus      -6.742884     20.0    9    None

[117 rows x 7 columns]

In [45]:
success = estimate(net, init='flat', tolerance=1e-06, maximum_iterations=100,ref_power=100000000)
print(success)

True

In [46]:
net.res_bus_est

       vm_pu  va_degree           p_kw         q_kvar
0   1.039396 -13.537179   97603.606114   44194.010143
1   1.048510  -9.785407     -25.210091      -8.216616
2   1.013397  -8.937270     -12.636706      -0.753806
3   1.000819  -8.999185    8531.336693   88035.877015
4   1.014935  -8.930347      15.300779      -4.622773
5   1.012334 -10.715748       6.489708       2.344663
6   1.016206 -11.346161  320045.251975  153028.010768
7   1.032546 -10.034093  328980.240332   32295.821048
8   1.034256 -11.117058      39.267974      20.941961
9   1.031590 -11.986578  157996.313852   30022.979150
10  1.050138  -5.410678     -28.686496      18.051815
11  0.991044  -6.821517  679994.190470  103009.250081
12  1.030726 -12.276530  321963.350629    2373.274386
13  1.032354  -7.629945  274004.265616  114982.502346
14  1.050183  -3.184922      22.028551     -23.624312
15  1.045187  -3.383069  247501.738017   84594.592511
16  1.038029  -9.914546  308582.472293  -92184.030684
17  1.057697  -8.369361  223975.256035   47207.079781
18  1.052575  -9.439205  139015.938776   16979.624749
19  1.038359 -11.362652  281005.654045   75539.524103
20  1.050384  -5.928724  206001.275941   27603.472101
21  1.050124  -3.170233  283488.744946   26910.842288
22  1.049916  -7.370581 -250011.268225 -161767.045833
23  1.004474 -12.626990  499999.898791  184002.199011
24  0.982006   0.000000 -668696.927441 -216958.836361
25  0.984111  -0.189381 -649968.327757 -206960.209827
26  0.997230  -0.194193 -631987.656288 -108298.835585
27  1.012340  -1.631676 -508017.799412 -166730.597501
28  1.049439   1.774231 -649987.687085 -210662.752236
29  1.063650   4.465567 -559972.912273 -100193.172532
30  1.027512  -1.583258 -539994.847565    1382.162220
31  1.026508   3.892357 -830001.105177  -21725.682108
32  1.030009 -14.536098  104041.654529  171555.910940
33  1.006018 -11.192565      -3.995634       3.099356
34  1.008237 -10.408551     -22.817308     -16.475436
35  0.998409 -12.755905  233828.207114   83992.249097
36  0.997884 -13.336091  521987.319654  176615.537742
37  1.038343 -14.179028    6497.915417  -66607.409941
38  1.017855  -8.171249     -36.356540       6.684309

In [39]:
pp.runpp(net)

In [40]:
net.res_bus

       vm_pu  va_degree           p_kw         q_kvar
0   1.039384 -13.536602   97600.000000   44200.000000
1   1.048494  -9.785267       0.000000       0.000000
10  1.013386  -8.936966       0.000000       0.000000
11  1.000815  -8.998824    8530.000000   88000.000000
12  1.014923  -8.929927       0.000000       0.000000
13  1.012319 -10.715295       0.000000       0.000000
14  1.016185 -11.345399  320000.000000  153000.000000
15  1.032520 -10.033348  329000.000000   32300.000000
16  1.034237 -11.116436       0.000000       0.000000
17  1.031573 -11.986168  158000.000000   30000.000000
18  1.050107  -5.410073       0.000000       0.000000
19  0.991011  -6.821178  680000.000000  103000.000000
2   1.030708 -12.276384  322000.000000    2400.000000
20  1.032319  -7.628746  274000.000000  115000.000000
21  1.050143  -3.183120       0.000000       0.000000
22  1.045145  -3.381276  247500.000000   84600.000000
23  1.038001  -9.913759  308600.000000  -92200.000000
24  1.057683  -8.369235  224000.000000   47200.000000
25  1.052561  -9.438770  139000.000000   17000.000000
26  1.038345 -11.362152  281000.000000   75500.000000
27  1.050374  -5.928359  206000.000000   27600.000000
28  1.050115  -3.169874  283500.000000   26900.000000
29  1.049900  -7.370475 -250000.000000 -161761.648109
3   1.004460 -12.626734  500000.000000  184000.000000
30  0.982000   0.000000 -668671.125556 -216974.486200
31  0.984100  -0.188437 -650000.000000 -206964.854885
32  0.997200  -0.193174 -632000.000000 -108292.786122
33  1.012300  -1.631119 -508000.000000 -166688.369275
34  1.049400   1.776507 -650000.000000 -210661.383702
35  1.063600   4.468437 -560000.000000 -100164.792278
36  1.027500  -1.582899 -540000.000000    1369.447491
37  1.026500   3.892818 -830000.000000  -21732.728859
38  1.030000 -14.535256  104000.000000  171532.640896
4   1.006006 -11.192339       0.000000       0.000000
5   1.008226 -10.408330       0.000000       0.000000
6   0.998397 -12.755626  233800.000000   84000.000000
7   0.997872 -13.335844  522000.000000  176600.000000
8   1.038332 -14.178442    6500.000000  -66600.000000
9   1.017843  -8.170875       0.000000       0.000000

[Bus Parameters](https://pandapower.readthedocs.io/en/v1.6.0/elements/bus.html#input-parameters)

In [36]:
net.bus # show bus table

    in_service  max_vm_pu  min_vm_pu name type  vn_kv zone
0         True       1.06       0.94    1    b  345.0    2
1         True       1.06       0.94    2    b  345.0    2
10        True       1.06       0.94   11    b  345.0    1
11        True       1.06       0.94   12    b  345.0    1
12        True       1.06       0.94   13    b  345.0    1
13        True       1.06       0.94   14    b  345.0    1
14        True       1.06       0.94   15    b  345.0    3
15        True       1.06       0.94   16    b  345.0    3
16        True       1.06       0.94   17    b  345.0    2
17        True       1.06       0.94   18    b  345.0    2
18        True       1.06       0.94   19    b  345.0    3
19        True       1.06       0.94   20    b  345.0    3
2         True       1.06       0.94    3    b  345.0    2
20        True       1.06       0.94   21    b  345.0    3
21        True       1.06       0.94   22    b  345.0    3
22        True       1.06       0.94   23    b  345.0    3
23        True       1.06       0.94   24    b  345.0    3
24        True       1.06       0.94   25    b  345.0    2
25        True       1.06       0.94   26    b  345.0    2
26        True       1.06       0.94   27    b  345.0    2
27        True       1.06       0.94   28    b  345.0    3
28        True       1.06       0.94   29    b  345.0    3
29        True       1.06       0.94   30    b  345.0    2
3         True       1.06       0.94    4    b  345.0    1
30        True       1.06       0.94   31    b  345.0    1
31        True       1.06       0.94   32    b  345.0    1
32        True       1.06       0.94   33    b  345.0    3
33        True       1.06       0.94   34    b  345.0    3
34        True       1.06       0.94   35    b  345.0    3
35        True       1.06       0.94   36    b  345.0    3
36        True       1.06       0.94   37    b  345.0    2
37        True       1.06       0.94   38    b  345.0    3
38        True       1.06       0.94   39    b  345.0    1
4         True       1.06       0.94    5    b  345.0    1
5         True       1.06       0.94    6    b  345.0    1
6         True       1.06       0.94    7    b  345.0    1
7         True       1.06       0.94    8    b  345.0    1
8         True       1.06       0.94    9    b  345.0    1
9         True       1.06       0.94   10    b  345.0    1

[External Grid Parameters](https://pandapower.readthedocs.io/en/v1.6.0/elements/ext_grid.html#input-parameters)

In [37]:
net.ext_grid #show external grid table

,bus,in_service,max_p_kw,max_q_kvar,min_p_kw,min_q_kvar,name,va_degree,vm_pu
0,30,True,0.0,100000.0,-646000.0,-300000.0,None,0.0,0.982

[Transfromer Parameters](https://pandapower.readthedocs.io/en/v1.6.0/elements/trafo.html#input-parameters)

In [38]:
net.trafo #show transformer table

,df,hv_bus,i0_percent,in_service,lv_bus,max_loading_percent,name,parallel,pfe_kw,shift_degree,...,tp_min,tp_phase_shifter,tp_pos,tp_side,tp_st_degree,tp_st_percent,vn_hv_kv,vn_lv_kv,vsc_percent,vscr_percent
0,1.0,1,0.0,True,29,100.0,None,1,0.0,0.0,...,NaN,False,1,hv,NaN,2.5,345.0,345.0,16.290000,0.00
1,1.0,5,0.0,True,30,100.0,None,1,0.0,0.0,...,NaN,False,1,hv,NaN,7.0,345.0,345.0,45.000000,0.00
10,1.0,28,0.0,True,37,100.0,None,1,0.0,0.0,...,NaN,False,1,hv,NaN,2.5,345.0,345.0,18.744599,0.96
2,1.0,9,0.0,True,31,100.0,None,1,0.0,0.0,...,NaN,False,1,hv,NaN,7.0,345.0,345.0,18.000000,0.00
3,1.0,11,0.0,True,10,100.0,None,1,0.0,0.0,...,NaN,False,1,hv,NaN,0.6,345.0,345.0,21.764708,0.80
4,1.0,11,0.0,True,12,100.0,None,1,0.0,0.0,...,NaN,False,1,hv,NaN,0.6,345.0,345.0,21.764708,0.80
5,1.0,18,0.0,True,19,100.0,None,1,0.0,0.0,...,NaN,False,1,hv,NaN,6.0,345.0,345.0,12.435968,0.63
6,1.0,18,0.0,True,32,100.0,None,1,0.0,0.0,...,NaN,False,1,hv,NaN,7.0,345.0,345.0,12.795519,0.63
7,1.0,19,0.0,True,33,100.0,None,1,0.0,0.0,...,NaN,False,1,hv,NaN,0.9,345.0,345.0,16.220237,0.81
8,1.0,21,0.0,True,34,100.0,None,1,0.0,0.0,...,NaN,False,1,hv,NaN,2.5,345.0,345.0,12.870000,0.00
9,1.0,24,0.0,True,36,100.0,None,1,0.0,0.0,...,NaN,False,1,hv,NaN,2.5,345.0,345.0,20.886982,0.54

[Line Parameters](https://pandapower.readthedocs.io/en/v1.6.0/elements/line.html#input-parameters)

In [39]:
net.line # show line table

,c_nf_per_km,df,from_bus,g_us_per_km,in_service,length_km,max_i_ka,max_loading_percent,name,parallel,r_ohm_per_km,std_type,to_bus,type,x_ohm_per_km
0,1557.117675,1.0,0,0.0,True,1.0,1.004087,100.0,None,1,4.165875,None,1,ol,48.919275
1,1671.444477,1.0,0,0.0,True,1.0,1.673479,100.0,None,1,1.190250,None,38,ol,29.756250
10,251.830968,1.0,5,0.0,True,1.0,1.506131,100.0,None,1,0.714150,None,6,ol,10.950300
11,309.551517,1.0,5,0.0,True,1.0,0.803270,100.0,None,1,0.833175,None,10,ol,9.760050
12,173.830226,1.0,6,0.0,True,1.0,1.506131,100.0,None,1,0.476100,None,7,ol,5.475150
13,847.756639,1.0,7,0.0,True,1.0,1.506131,100.0,None,1,2.737575,None,8,ol,43.206075
14,2674.311163,1.0,8,0.0,True,1.0,1.506131,100.0,None,1,1.190250,None,38,ol,29.756250
15,162.464403,1.0,9,0.0,True,1.0,1.004087,100.0,None,1,0.476100,None,10,ol,5.118075
16,162.464403,1.0,9,0.0,True,1.0,1.004087,100.0,None,1,0.476100,None,12,ol,5.118075
17,383.986511,1.0,12,0.0,True,1.0,1.004087,100.0,None,1,1.071225,None,13,ol,12.021525
18,815.664905,1.0,13,0.0,True,1.0,1.004087,100.0,None,1,2.142450,None,14,ol,25.828425
19,381.089341,1.0,14,0.0,True,1.0,1.004087,100.0,None,1,1.071225,None,15,ol,11.188350
2,573.194026,1.0,1,0.0,True,1.0,0.836740,100.0,None,1,1.547325,None,2,ol,17.972775
20,299.077132,1.0,15,0.0,True,1.0,1.004087,100.0,None,1,0.833175,None,16,ol,10.593225
21,677.492161,1.0,15,0.0,True,1.0,1.004087,100.0,None,1,1.904400,None,18,ol,23.209875
22,567.845404,1.0,15,0.0,True,1.0,1.004087,100.0,None,1,0.952200,None,20,ol,16.068375
23,151.544299,1.0,15,0.0,True,1.0,1.004087,100.0,None,1,0.357075,None,23,ol,7.022475
24,293.951369,1.0,16,0.0,True,1.0,1.004087,100.0,None,1,0.833175,None,17,ol,9.760050
25,716.715392,1.0,16,0.0,True,1.0,1.004087,100.0,None,1,1.547325,None,26,ol,20.591325
26,571.634011,1.0,20,0.0,True,1.0,1.506131,100.0,None,1,0.952200,None,21,ol,16.663500
27,411.398201,1.0,21,0.0,True,1.0,1.004087,100.0,None,1,0.714150,None,22,ol,11.426400
28,804.521942,1.0,22,0.0,True,1.0,1.004087,100.0,None,1,2.618550,None,23,ol,41.658750
29,0.000000,1.0,22,0.0,True,1.0,1.506131,100.0,None,1,0.595125,None,35,ol,32.374800
3,325.374525,1.0,1,0.0,True,1.0,0.836740,100.0,None,1,8.331750,None,24,ol,10.236150
30,1183.382690,1.0,24,0.0,True,1.0,1.004087,100.0,None,1,3.808800,None,25,ol,38.445075
31,533.970796,1.0,25,0.0,True,1.0,1.004087,100.0,None,1,1.666350,None,26,ol,17.496675
32,1738.747975,1.0,25,0.0,True,1.0,1.004087,100.0,None,1,5.118075,None,27,ol,56.417850
33,2293.221822,1.0,25,0.0,True,1.0,1.004087,100.0,None,1,6.784425,None,28,ol,74.390625
34,554.919566,1.0,27,0.0,True,1.0,1.004087,100.0,None,1,1.666350,None,28,ol,17.972775
4,493.410410,1.0,2,0.0,True,1.0,0.836740,100.0,None,1,1.547325,None,3,ol,25.352325
5,476.473106,1.0,2,0.0,True,1.0,0.836740,100.0,None,1,1.309275,None,17,ol,15.830325
6,299.077132,1.0,3,0.0,True,1.0,1.004087,100.0,None,1,0.952200,None,4,ol,15.235200
7,307.991502,1.0,3,0.0,True,1.0,0.836740,100.0,None,1,0.952200,None,13,ol,15.354225
8,96.720920,1.0,4,0.0,True,1.0,2.008175,100.0,None,1,0.238050,None,5,ol,3.094650
9,328.940273,1.0,4,0.0,True,1.0,1.506131,100.0,None,1,0.952200,None,7,ol,13.330800

In [40]:
net.switch # show switch table

Empty DataFrame
Columns: [bus, element, et, type, closed, name]
Index: []

[Load Parameters](https://pandapower.readthedocs.io/en/v1.6.0/elements/load.html#input-parameters)

In [41]:
net.load

,bus,const_i_percent,const_z_percent,controllable,in_service,name,p_kw,q_kvar,scaling,sn_kva,type
0,0,0.0,0.0,False,True,None,97600.0,44200.0,1.0,NaN,None
1,2,0.0,0.0,False,True,None,322000.0,2400.0,1.0,NaN,None
10,19,0.0,0.0,False,True,None,680000.0,103000.0,1.0,NaN,None
11,20,0.0,0.0,False,True,None,274000.0,115000.0,1.0,NaN,None
12,22,0.0,0.0,False,True,None,247500.0,84600.0,1.0,NaN,None
13,23,0.0,0.0,False,True,None,308600.0,-92200.0,1.0,NaN,None
14,24,0.0,0.0,False,True,None,224000.0,47200.0,1.0,NaN,None
15,25,0.0,0.0,False,True,None,139000.0,17000.0,1.0,NaN,None
16,26,0.0,0.0,False,True,None,281000.0,75500.0,1.0,NaN,None
17,27,0.0,0.0,False,True,None,206000.0,27600.0,1.0,NaN,None
18,28,0.0,0.0,False,True,None,283500.0,26900.0,1.0,NaN,None
19,30,0.0,0.0,False,True,None,9200.0,4600.0,1.0,NaN,None
2,3,0.0,0.0,False,True,None,500000.0,184000.0,1.0,NaN,None
20,38,0.0,0.0,False,True,None,1104000.0,250000.0,1.0,NaN,None
3,6,0.0,0.0,False,True,None,233800.0,84000.0,1.0,NaN,None
4,7,0.0,0.0,False,True,None,522000.0,176600.0,1.0,NaN,None
5,8,0.0,0.0,False,True,None,6500.0,-66600.0,1.0,NaN,None
6,11,0.0,0.0,False,True,None,8530.0,88000.0,1.0,NaN,None
7,14,0.0,0.0,False,True,None,320000.0,153000.0,1.0,NaN,None
8,15,0.0,0.0,False,True,None,329000.0,32300.0,1.0,NaN,None
9,17,0.0,0.0,False,True,None,158000.0,30000.0,1.0,NaN,None

In [42]:
net.sgen # static generator

Empty DataFrame
Columns: [name, bus, p_kw, q_kvar, sn_kva, scaling, in_service, type]
Index: []

[Generator Parameters](https://pandapower.readthedocs.io/en/v1.6.0/elements/gen.html#input-parameters)

In [43]:
net.gen # voltage controlled generator

,bus,controllable,in_service,max_p_kw,max_q_kvar,min_p_kw,min_q_kvar,name,p_kw,scaling,sn_kva,type,vm_pu
0,29,True,True,0.0,-140000.0,-1040000.0,-400000.0,None,-250000.0,1.0,NaN,None,1.0499
1,31,True,True,0.0,-150000.0,-725000.0,-300000.0,None,-650000.0,1.0,NaN,None,0.9841
2,32,True,True,0.0,0.0,-652000.0,-250000.0,None,-632000.0,1.0,NaN,None,0.9972
3,33,True,True,0.0,0.0,-508000.0,-167000.0,None,-508000.0,1.0,NaN,None,1.0123
4,34,True,True,0.0,100000.0,-687000.0,-300000.0,None,-650000.0,1.0,NaN,None,1.0494
5,35,True,True,0.0,0.0,-580000.0,-240000.0,None,-560000.0,1.0,NaN,None,1.0636
6,36,True,True,0.0,0.0,-564000.0,-250000.0,None,-540000.0,1.0,NaN,None,1.0275
7,37,True,True,0.0,150000.0,-865000.0,-300000.0,None,-830000.0,1.0,NaN,None,1.0265
8,38,True,True,0.0,100000.0,-1100000.0,-300000.0,None,-1000000.0,1.0,NaN,None,1.0300

In [ ]:
net.shunt

In [ ]:
plot.simple_plot(net)

In [ ]:
colors = ["b", "g", "r", "c", "y"]
lc = plot.create_line_collection(net, net.line.index, color=colors[0], zorder=1) #create lines
bc = plot.create_bus_collection(net, net.bus.index, size=0.1, color=colors[0], zorder=2) #create buses
plot.draw_collections([lc,bc], figsize=(8,6)) # plot lines and buses

In [ ]:
buses = net.bus.index.tolist() # list of all bus indices
coords = zip(net.bus_geodata.x.loc[buses].values+0.1, net.bus_geodata.y.loc[buses].values+0.1) # tuples of all bus coords

bic = plot.create_annotation_collection(size=0.2, texts=np.char.mod('%d', buses), coords=coords, zorder=3, color=colors[1])
plot.draw_collections([lc, bc, bic], figsize=(80,60)) # plot lines, buses and bus indices